"""Splash fantasy contest domain models and parsers."""

from src.fantasy.splash.client import (
    SplashPublicFetchResult,
    SplashReadOnlyClient,
    contest_id_from_ref,
    league_id_from_lobby_url,
    slate_id_from_contest_detail,
)
from src.fantasy.splash.contest_evaluator import (
    SplashLobbyEvaluationConfig,
    build_splash_lobby_evaluation,
)
from src.fantasy.splash.lineup_simulator import (
    lineup_from_players,
    outcomes_from_score_distributions,
    payout_for_rank,
    score_lineup,
    simulate_lineup_outcomes,
)
from src.fantasy.splash.mapping import (
    DataGolfPlayerReference,
    datagolf_references_from_rows,
    map_players_to_datagolf,
)
from src.fantasy.splash.models import (
    DataGolfScoreAnchor,
    SplashContest,
    SplashContestPlayerPool,
    SplashFantasyReport,
    SplashFantasyReportConfig,
    SplashLineup,
    SplashLineupDuplicationEstimate,
    SplashLineupPortfolio,
    SplashLineupSimulationResult,
    SplashManualLineup,
    SplashOpponentLineupAssumptions,
    SplashOpponentLineupPool,
    SplashOpponentSimulationResult,
    SplashOwnershipSensitivityReport,
    SplashOwnershipSensitivityScenario,
    SplashPayout,
    SplashPlayer,
    SplashPlayerMapping,
    SplashPlayerMappingReviewItem,
    SplashPlayerScoreDistribution,
    SplashPortfolioCandidate,
    SplashPortfolioEntry,
    SplashPortfolioOptimizationConfig,
    SplashRosterRule,
    SplashScoringConfig,
    SplashScoringRule,
    SplashSlate,
    SplashTier,
)
from src.fantasy.splash.opponent_lineups import (
    generate_opponent_lineup_pool,
    run_opponent_ownership_sensitivity,
    simulate_lineup_with_generated_opponents,
)
from src.fantasy.splash.parser import (
    parse_contest_detail,
    parse_contest_player_pool,
    parse_player_pool,
)
from src.fantasy.splash.portfolio_optimizer import (
    evaluate_lineup_candidates,
    generate_projected_tier_valid_lineups,
    generate_tier_valid_lineups,
    optimize_lineup_portfolio,
    portfolio_candidate_from_result,
    portfolio_config,
)
from src.fantasy.splash.report import (
    build_splash_fantasy_report,
    fantasy_report_config,
)
from src.fantasy.splash.scoring_model import (
    datagolf_score_anchor_from_row,
    score_distributions_to_records,
    simulate_player_score_distributions,
    splash_scoring_config_from_rules,
)
from src.fantasy.splash.storage import persist_raw_snapshot

__all__ = [
    "DataGolfPlayerReference",
    "DataGolfScoreAnchor",
    "SplashPublicFetchResult",
    "SplashReadOnlyClient",
    "SplashContest",
    "SplashContestPlayerPool",
    "SplashFantasyReport",
    "SplashFantasyReportConfig",
    "SplashLineup",
    "SplashLobbyEvaluationConfig",
    "SplashLineupDuplicationEstimate",
    "SplashLineupPortfolio",
    "SplashLineupSimulationResult",
    "SplashManualLineup",
    "SplashOpponentLineupAssumptions",
    "SplashOpponentLineupPool",
    "SplashOpponentSimulationResult",
    "SplashOwnershipSensitivityReport",
    "SplashOwnershipSensitivityScenario",
    "SplashPayout",
    "SplashPlayer",
    "SplashPlayerMapping",
    "SplashPlayerMappingReviewItem",
    "SplashPlayerScoreDistribution",
    "SplashPortfolioCandidate",
    "SplashPortfolioEntry",
    "SplashPortfolioOptimizationConfig",
    "SplashRosterRule",
    "SplashScoringRule",
    "SplashScoringConfig",
    "SplashSlate",
    "SplashTier",
    "build_splash_fantasy_report",
    "build_splash_lobby_evaluation",
    "contest_id_from_ref",
    "datagolf_references_from_rows",
    "datagolf_score_anchor_from_row",
    "evaluate_lineup_candidates",
    "fantasy_report_config",
    "generate_opponent_lineup_pool",
    "generate_projected_tier_valid_lineups",
    "generate_tier_valid_lineups",
    "lineup_from_players",
    "league_id_from_lobby_url",
    "map_players_to_datagolf",
    "outcomes_from_score_distributions",
    "payout_for_rank",
    "parse_contest_detail",
    "parse_contest_player_pool",
    "parse_player_pool",
    "persist_raw_snapshot",
    "optimize_lineup_portfolio",
    "portfolio_candidate_from_result",
    "portfolio_config",
    "score_distributions_to_records",
    "score_lineup",
    "simulate_lineup_outcomes",
    "simulate_lineup_with_generated_opponents",
    "simulate_player_score_distributions",
    "run_opponent_ownership_sensitivity",
    "slate_id_from_contest_detail",
    "splash_scoring_config_from_rules",
]
